### PR TITLE
feat: add conda env easy setup

### PR DESCRIPTION
**Pull request by kaminskypavel**
have the project up and runing with anaconda in no time

### CODE REVIEW

**Comment by michalfaber** [comment]
Hi @kaminskypavel I tried to run the command on my osx but got NoPackagesFoundError: Packages missing in current osx-64 channels.

**Comment by kaminskypavel** [comment]
Can you copy paste what exact packages are missing?

**Comment by michalfaber** [comment]
I use conda ver: 4.2.9 and here is the output:

> conda env create -f keras-openpose.yaml                                                                                                                                                  
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: .
NoPackagesFoundError: Packages missing in current osx-64 channels:
  - bzip2 1.0.6 vc14_3
  - freetype 2.5.5 vc14_2
  - olefile 0.44 py36h0a7bdd2_0
  - icu 58.2 vc14_0
  - jpeg 9b vc14_2
  - libpng 1.6.28 vc14_2
  - libtiff 4.0.7 vc14_1
  - libwebp 0.5.2 vc14_7
  - opencv 3.3.0 py36_202
  - openssl 1.0.2l vc14_0
  - qt 5.6.2 vc14_1
  - vc 14 0
.....

**Comment by kaminskypavel** [comment]
@michalfaber, you're correct. I've just added a macOs env file too. I've also tested it and it looks fine.
can you please confirm it works on your end and merge?

**Comment by michalfaber** [comment]
Is this file dependent on the python 3.6 ? 
Now I got the same error but different packages missing:
```
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: .
NoPackagesFoundError: Packages missing in current osx-64 channels:
  - appnope 0.1.0 py36hf537a9a_0
  - ca-certificates 2017.08.26 ha1e5d58_0
  - certifi 2017.11.5 py36ha569be9_0
  - decorator 4.1.2 py36h69a1b52_0
  - h5py 2.7.1 py36h39cdac5_0
....
```

**Pull request closed without merging**
